name: Build

on: [push]

jobs:

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image & push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest
          REPO=${{ github.repository }}
          REPO=${REPO,,}
          docker build -t ghcr.io/${REPO}:${VERSION} . 
          docker push ghcr.io/${REPO}:${VERSION}
          if [ "$VERSION" != "latest" ] ; then
            docker tag ghcr.io/${REPO}:${VERSION} ghcr.io/${REPO}:latest
            docker push ghcr.io/${REPO}:latest
          fi